// Mock data for dashboard UI — replace with real DB queries once backend is wired up

export const mockUser = {
  id: "user_1",
  name: "John Doe",
  email: "john@example.com",
  image: null,
  isPro: false,
};

export const mockItemTypes = [
  { id: "type_snippet", name: "snippet", icon: "Code", color: "#3b82f6", isSystem: true, userId: null },
  { id: "type_prompt", name: "prompt", icon: "Sparkles", color: "#8b5cf6", isSystem: true, userId: null },
  { id: "type_command", name: "command", icon: "Terminal", color: "#f97316", isSystem: true, userId: null },
  { id: "type_note", name: "note", icon: "StickyNote", color: "#fde047", isSystem: true, userId: null },
  { id: "type_file", name: "file", icon: "File", color: "#6b7280", isSystem: true, userId: null },
  { id: "type_image", name: "image", icon: "Image", color: "#ec4899", isSystem: true, userId: null },
  { id: "type_link", name: "link", icon: "Link", color: "#10b981", isSystem: true, userId: null },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    itemCount: 12,
    userId: "user_1",
    defaultTypeId: "type_snippet",
    createdAt: "2026-01-10T00:00:00Z",
    updatedAt: "2026-01-10T00:00:00Z",
  },
  {
    id: "col_2",
    name: "Python Snippets",
    description: "Useful Python code snippets",
    isFavorite: false,
    itemCount: 8,
    userId: "user_1",
    defaultTypeId: "type_snippet",
    createdAt: "2026-01-11T00:00:00Z",
    updatedAt: "2026-01-11T00:00:00Z",
  },
  {
    id: "col_3",
    name: "Context Files",
    description: "AI context files for projects",
    isFavorite: true,
    itemCount: 5,
    userId: "user_1",
    defaultTypeId: "type_file",
    createdAt: "2026-01-12T00:00:00Z",
    updatedAt: "2026-01-12T00:00:00Z",
  },
  {
    id: "col_4",
    name: "Interview Prep",
    description: "Technical interview preparation",
    isFavorite: false,
    itemCount: 24,
    userId: "user_1",
    defaultTypeId: "type_note",
    createdAt: "2026-01-13T00:00:00Z",
    updatedAt: "2026-01-13T00:00:00Z",
  },
  {
    id: "col_5",
    name: "Git Commands",
    description: "Frequently used git commands",
    isFavorite: true,
    itemCount: 15,
    userId: "user_1",
    defaultTypeId: "type_command",
    createdAt: "2026-01-14T00:00:00Z",
    updatedAt: "2026-01-14T00:00:00Z",
  },
  {
    id: "col_6",
    name: "AI Prompts",
    description: "Curated AI prompts for coding",
    isFavorite: false,
    itemCount: 18,
    userId: "user_1",
    defaultTypeId: "type_prompt",
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
  },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useAuth Hook",
    contentType: "text" as const,
    content: "Custom authentication hook for React applications",
    description: "Custom authentication hook for React applications",
    language: "typescript",
    isFavorite: true,
    isPinned: true,
    lastUsedAt: "2026-01-15T00:00:00Z",
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
    userId: "user_1",
    itemTypeId: "type_snippet",
    tags: ["react", "auth", "hooks"],
    collectionIds: ["col_1"],
  },
  {
    id: "item_2",
    title: "API Error Handling Pattern",
    contentType: "text" as const,
    content: "Fetch wrapper with exponential backoff retry logic",
    description: "Fetch wrapper with exponential backoff retry logic",
    language: "typescript",
    isFavorite: false,
    isPinned: true,
    lastUsedAt: "2026-01-15T00:00:00Z",
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-01-15T00:00:00Z",
    userId: "user_1",
    itemTypeId: "type_snippet",
    tags: ["api", "error-handling", "fetch"],
    collectionIds: ["col_1"],
  },
  {
    id: "item_3",
    title: "Git Rebase Interactive",
    contentType: "text" as const,
    content: "git rebase -i HEAD~3",
    description: "Interactively rebase the last 3 commits",
    language: null,
    isFavorite: false,
    isPinned: false,
    lastUsedAt: "2026-01-14T00:00:00Z",
    createdAt: "2026-01-14T00:00:00Z",
    updatedAt: "2026-01-14T00:00:00Z",
    userId: "user_1",
    itemTypeId: "type_command",
    tags: ["git", "rebase"],
    collectionIds: ["col_5"],
  },
  {
    id: "item_4",
    title: "Code Review Prompt",
    contentType: "text" as const,
    content: "Review the following code for bugs, performance issues, and best practices...",
    description: "Curated AI prompt for code reviews",
    language: null,
    isFavorite: false,
    isPinned: false,
    lastUsedAt: "2026-01-13T00:00:00Z",
    createdAt: "2026-01-13T00:00:00Z",
    updatedAt: "2026-01-13T00:00:00Z",
    userId: "user_1",
    itemTypeId: "type_prompt",
    tags: ["code-review", "ai"],
    collectionIds: ["col_6"],
  },
  {
    id: "item_5",
    title: "Big O Cheat Sheet",
    contentType: "text" as const,
    content: "Time complexity reference for common data structures and algorithms",
    description: "Time complexity reference for common data structures and algorithms",
    language: null,
    isFavorite: false,
    isPinned: false,
    lastUsedAt: "2026-01-12T00:00:00Z",
    createdAt: "2026-01-12T00:00:00Z",
    updatedAt: "2026-01-12T00:00:00Z",
    userId: "user_1",
    itemTypeId: "type_note",
    tags: ["algorithms", "interview"],
    collectionIds: ["col_4"],
  },
];

// Counts per item type — used for sidebar nav badges
export const mockItemTypeCounts: Record<string, number> = {
  type_snippet: 24,
  type_prompt: 19,
  type_command: 15,
  type_note: 12,
  type_file: 5,
  type_image: 5,
  type_link: 8,
};
